version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: blogv2-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: BlogV2Testing
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d BlogV2Testing" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - blogv2-network
    volumes:
      - blogv2-postgres-data:/var/lib/postgresql

  redis-cache:
    container_name: blogv2-redis
    image: redis:7-alpine
    ports:
      - "6400:6379"
    networks:
      - blogv2-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: blogv2-image:latest
    container_name: blogv2-app
    ports:
      - "9080:8092"
    depends_on:
      postgres:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BlogV2Testing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: blogv2-redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_REDIS_HOST: blogv2-redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      IMAGEKIT_PUBLIC_KEY: ${IMAGEKIT_PUBLIC}
      IMAGEKIT_PRIVATE_KEY: ${IMAGEKIT_PRIVATE}
      IMAGEKIT_URL_ENDPOINT: ${IMAGEKIT_URL}
      ADMIN_SECRET: ${ADMIN_SECRET}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    networks:
      - blogv2-network

  prometheus:
    image: prom/prometheus:latest
    container_name: blogv2-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - blogv2-network
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: blogv2-grafana
    ports:
      - "3000:3000"
    networks:
      - blogv2-network
    depends_on:
      - prometheus

networks:
  blogv2-network:
    driver: bridge

volumes:
  blogv2-postgres-data: