spring:
  application:
    name: BlogV2
  profiles:
    active: dev

imagekit:
  public-key: ${IMAGEKIT_PUBLIC_KEY}
  private-key: ${IMAGEKIT_PRIVATE_KEY}
  url-endpoint: ${IMAGEKIT_URL_ENDPOINT}

app:
  admin:
    secret: ${ADMIN_SECRET:default_admin_secret}
